import { 
  ShiftSchedule, 
  HDMachine, 
  MachineAssignment, 
  UserAccount, 
  UserRole,
  Nurse, 
  NurseRole,
  Machine, 
  ShiftAssignment, 
  ShiftType, 
  AppSettings,
  Doctor,
  DoctorShiftDuty,
  DoctorRole,
  SpecialTask,
  SpecialTaskCategory,
  SPECIAL_TASK_DEFINITIONS
} from '../types';
import { GoogleSheetsService, PartialSyncTargets, DEFAULT_PARTIAL_SYNC_TARGETS } from '../domain/GoogleSheetsService';
export type { PartialSyncTargets };
export { DEFAULT_PARTIAL_SYNC_TARGETS };
import { ScheduleImportService } from '../domain/ScheduleImportService';
import { FairSchedulerEngine } from '../domain/FairSchedulerEngine';
import { 
  generateMonthlySchedule, 
  sortNursesByShiftScheduleOrder, 
  getEffectiveShiftForEmployee,
  autoAssignMachinesForShift
} from './scheduler';
import { isInvalidNurseAccount } from './storage';

export interface SyncPayloadData {
  monthPrefix: string;
  domainNurses: Nurse[];
  domainMachines: Machine[];
  domainMonthlyAssignments: ShiftAssignment[];
  bays: string[];
  domainDoctors: Doctor[];
  doctorDuties: Record<string, DoctorShiftDuty>;
  autoGeneratedSchedules?: ShiftSchedule[];
  autoGeneratedMachineAssignments?: MachineAssignment[];
  specialTasks?: SpecialTask[];
  employees?: UserAccount[];
}

function parseSimpleCsv(text: string): string[][] {
  const lines = text.split(/\r?\n/).filter((l) => l.trim().length > 0);
  return lines.map((line) => {
    const row: string[] = [];
    let insideQuotes = false;
    let currentCell = '';
    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      if (char === '"') {
        if (insideQuotes && line[i + 1] === '"') {
          currentCell += '"';
          i++;
        } else {
          insideQuotes = !insideQuotes;
        }
      } else if (char === ',' && !insideQuotes) {
        row.push(currentCell.trim());
        currentCell = '';
      } else {
        currentCell += char;
      }
    }
    row.push(currentCell.trim());
    return row;
  });
}

function parseDoctorsCsv(csvText: string): Doctor[] {
  const rows = parseSimpleCsv(csvText);
  if (rows.length < 2) return [];
  const doctors: Doctor[] = [];
  for (let i = 1; i < rows.length; i++) {
    const r = rows[i];
    if (!r[1] || r[1] === '-') continue;
    const id = Number(r[0]) || i;
    const name = r[1];
    const sip = r[2] || '';
    const phone = r[3] || '';
    const roleRaw = (r[4] || '').toUpperCase();
    const role: DoctorRole = roleRaw.includes('DPJP') ? 'DPJP' : 'DOKTER_RUANGAN';
    const specialization = r[5] || 'Dokter Jaga Hemodialisa';
    const isActive = (r[6] || '').toUpperCase() !== 'NONAKTIF';
    doctors.push({ id, name, sip, phone, role, specialization, isActive });
  }
  return doctors;
}

function normalizeDoctorDutyDate(rawDate?: string): string | null {
  if (!rawDate) return null;
  const trimmed = rawDate.trim();
  if (!trimmed || trimmed.startsWith('#')) return null;

  // YYYY-MM-DD or YYYY/MM/DD
  const isoMatch = trimmed.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/);
  if (isoMatch) {
    return `${isoMatch[1]}-${isoMatch[2].padStart(2, '0')}-${isoMatch[3].padStart(2, '0')}`;
  }

  // DD/MM/YYYY or DD-MM-YYYY
  const dmyMatch = trimmed.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})/);
  if (dmyMatch) {
    return `${dmyMatch[3]}-${dmyMatch[2].padStart(2, '0')}-${dmyMatch[1].padStart(2, '0')}`;
  }

  return null;
}

function parseDoctorDutiesCsv(csvText: string): Record<string, DoctorShiftDuty> {
  const rows = parseSimpleCsv(csvText);
  if (rows.length < 2) return {};
  const duties: Record<string, DoctorShiftDuty> = {};
  for (let i = 1; i < rows.length; i++) {
    const r = rows[i];
    const rawDate = r[0];
    const date = normalizeDoctorDutyDate(rawDate);
    if (!date) continue;
    const pagiDoc = r[2] || '-';
    const siangDoc = r[3] || '-';
    const pagiId = r[4] || '';
    const siangId = r[5] || '';
    const notes = r[6] || '';
    duties[date] = {
      date,
      pagiDoctorId: pagiId,
      pagiDoctorName: pagiDoc,
      siangDoctorId: siangId,
      siangDoctorName: siangDoc,
      notes,
    };
  }
  return duties;
}

function parseNursesCsv(csvText: string): Nurse[] {
  const rows = parseSimpleCsv(csvText);
  if (rows.length < 2) return [];
  const nurses: Nurse[] = [];
  for (let i = 1; i < rows.length; i++) {
    const r = rows[i];
    if (!r[1] || r[1] === '-' || r[1].toLowerCase().includes('admin')) continue;
    if (r[1].includes('1790191588620') || (r[0] && String(r[0]).includes('1790191588620'))) continue;
    const id = Number(r[0]) || i;
    const name = r[1].trim();
    const nip = r[2] ? r[2].trim() : '';
    const phone = r[3] ? r[3].replace(/^'/, '').trim() : '';
    const roleRaw = (r[4] || '').toUpperCase();
    const role: NurseRole = roleRaw.includes('KARU') || roleRaw.includes('KEPALA')
      ? 'KARU'
      : roleRaw.includes('KATIM') || roleRaw.includes('PJ')
      ? 'KATIM'
      : 'PELAKSANA';
    const isActive = (r[5] || '').toUpperCase() !== 'NONAKTIF';
    const specialDuty = r[6] ? r[6].trim() : undefined;
    const defaultOffDay = r[7] !== undefined && r[7] !== '' ? Number(r[7]) : undefined;
    nurses.push({
      id,
      name,
      nip,
      phone,
      role,
      isActive,
      skillLevel: 'Senior',
      specialDuty: specialDuty || undefined,
      defaultOffDay: isNaN(Number(defaultOffDay)) ? undefined : Number(defaultOffDay),
    });
  }
  return nurses;
}

/**
 * Converts app state to domain models suitable for Google Sheets sync.
 */
export function prepareSyncPayload(
  schedules: ShiftSchedule[],
  employees: UserAccount[],
  machines: HDMachine[],
  machineAssignments: MachineAssignment[],
  monthPrefix: string,
  specialTasks: SpecialTask[] = []
): SyncPayloadData {
  const domainMachines: Machine[] = (machines || []).map((m, idx) => ({
    id: isNaN(Number(m.id)) ? idx + 1 : Number(m.id),
    code: m.code,
    name: `Mesin HD ${m.code}`,
    brandModel: (m as any).brandModel || m.model || 'Nipro / Fresenius',
    category: ((m as any).category || 'REGULER') as any,
    status: (m.status === 'siap' || m.status === 'dipakai' || m.status === 'AKTIF')
      ? 'AKTIF'
      : (m.status === 'maintenance' || m.status === 'MAINTENANCE')
      ? 'MAINTENANCE'
      : 'RUSAK',
    bay: m.bay || m.zone || 'Bay A',
    operationalShift: (m as any).operationalShift || 'ALL',
    notes: m.notes,
  }));

  // 1. Separate Nurses (strictly Kepala Ruang, PJ Shift, Perawat Pelaksana - NO ADMIN, NO DOKTER)
  // Sorted strictly by sortNursesByShiftScheduleOrder (matching Halaman Jadwal Shif matrix)
  const clinicalNurses = sortNursesByShiftScheduleOrder(
    (employees || []).filter(
      (e) => e.role === 'perawat' || e.role === 'pj_shift' || e.role === 'kepala_ruangan'
    )
  );

  const domainNurses: Nurse[] = clinicalNurses.map((e, idx) => ({
    id: isNaN(Number(e.nip)) ? (isNaN(Number(e.id)) ? idx + 1 : Number(e.id)) : Number(e.nip),
    name: e.name,
    nip: e.nip,
    phone: e.phone,
    role: e.role === 'kepala_ruangan' ? 'KARU' : e.role === 'pj_shift' ? 'KATIM' : 'PELAKSANA',
    isActive: e.status === 'aktif',
    skillLevel: e.skillLevel || 'Senior',
    specialDuty: e.specialDuty,
  }));

  const domainDoctors: Doctor[] = employees
    .filter((e) => e.role === 'dokter')
    .map((d, idx) => ({
      id: isNaN(Number(d.id)) ? 1000 + idx : Number(d.id),
      name: d.name,
      sip: d.nip || '',
      phone: d.phone || '',
      role: (d.specialization?.includes('DPJP') ? 'DPJP' : 'DOKTER_RUANGAN') as DoctorRole,
      specialization: d.specialization || 'Dokter Jaga Hemodialisa',
      isActive: d.status === 'aktif',
    }));

  const [yStr, mStr] = monthPrefix.split('-');
  const year = parseInt(yStr, 10) || 2026;
  const month = parseInt(mStr, 10) || 10;
  const daysInMonth = new Date(year, month, 0).getDate();

  // Check if month already has schedules in app state
  let effectiveMonthlySchedules = schedules.filter((s) => s.date.startsWith(monthPrefix));
  let effectiveMachineAssignments = machineAssignments || [];
  let autoGeneratedSchedules: ShiftSchedule[] | undefined = undefined;
  let autoGeneratedMachineAssignments: MachineAssignment[] | undefined = undefined;

  // If 0 schedules exist for this month (e.g. user selected another month),
  // auto-generate the complete fair schedule with FairSchedulerEngine
  if (effectiveMonthlySchedules.length === 0) {
    try {
      const fairAssignments = FairSchedulerEngine.generateMonthlySchedule(
        year,
        month,
        domainNurses,
        domainMachines
      );

      if (fairAssignments && fairAssignments.length > 0) {
        const genSchedules: ShiftSchedule[] = [];
        const genMachineAssignments: MachineAssignment[] = [];

        fairAssignments.forEach((fa) => {
          const emp = employees.find((e) => e.name.toLowerCase() === fa.nurseName.toLowerCase());
          const empId = emp ? emp.id : String(fa.nurseId);
          const shiftType = (fa.shiftType || 'LIBUR').toLowerCase() as ShiftType;

          genSchedules.push({
            id: `${empId}_${fa.date}`,
            employeeId: empId,
            date: fa.date,
            shift: shiftType,
            note: fa.notes || (fa.specialDuty ? `Tugas: ${fa.specialDuty}` : undefined),
            isCustomOverride: false,
          });

          if (fa.assignedMachineIds && fa.assignedMachineIds.length > 0 && shiftType !== 'libur') {
            const shiftSlot: 'pagi' | 'siang' = shiftType === 'siang' ? 'siang' : 'pagi';
            fa.assignedMachineIds.forEach((mId) => {
              const matchedMachine = machines.find((m) => String(m.id) === String(mId) || m.code.toUpperCase() === String(mId).toUpperCase());
              const machineKey = matchedMachine ? matchedMachine.id : String(mId);
              genMachineAssignments.push({
                id: `${empId}_${fa.date}_${shiftSlot}_${machineKey}`,
                machineId: machineKey,
                nurseId: empId,
                date: fa.date,
                shift: shiftSlot,
              });
            });
          }
        });

        // Add doctor schedules
        const doctorEmployees = employees.filter((e) => e.role === 'dokter');
        for (let d = 1; d <= daysInMonth; d++) {
          const dateStr = `${year}-${String(month).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
          const dayOfWeek = new Date(year, month - 1, d).getDay();
          const isSunday = dayOfWeek === 0;

          if (isSunday) {
            doctorEmployees.forEach((doc) => {
              genSchedules.push({
                id: `${doc.id}_${dateStr}`,
                employeeId: doc.id,
                date: dateStr,
                shift: 'libur',
                note: 'Pelayanan Tutup (Hari Minggu)',
                isCustomOverride: false,
              });
            });
          } else {
            const pagiDoc = doctorEmployees.find((doc) => doc.name.toLowerCase().includes('reza')) || doctorEmployees[0];
            const siangDoc = doctorEmployees.find((doc) => doc.name.toLowerCase().includes('paramitha')) || doctorEmployees[1] || doctorEmployees[0];
            if (pagiDoc) {
              genSchedules.push({
                id: `${pagiDoc.id}_${dateStr}`,
                employeeId: pagiDoc.id,
                date: dateStr,
                shift: 'pagi',
                note: 'Dokter Penanggung Jawab Pelayanan HD (DPJP)',
                isCustomOverride: false,
              });
            }
            if (siangDoc && siangDoc.id !== pagiDoc?.id) {
              genSchedules.push({
                id: `${siangDoc.id}_${dateStr}`,
                employeeId: siangDoc.id,
                date: dateStr,
                shift: 'siang',
                note: 'Dokter Jaga Ruangan Hemodialisa',
                isCustomOverride: false,
              });
            }
          }
        }

        effectiveMonthlySchedules = genSchedules;
        autoGeneratedSchedules = genSchedules;
        effectiveMachineAssignments = [...(machineAssignments || []), ...genMachineAssignments];
        autoGeneratedMachineAssignments = genMachineAssignments;
      }
    } catch (engineErr) {
      console.warn('[prepareSyncPayload] FairSchedulerEngine error, fallback to generateMonthlySchedule:', engineErr);
      const generated = generateMonthlySchedule(year, month - 1, employees, true, schedules);
      effectiveMonthlySchedules = generated;
      autoGeneratedSchedules = generated;
    }
  }

  // Build full monthly assignments covering EVERY day for every nurse in clinicalNurses
  // exactly matching the schedule matrix displayed on Halaman Jadwal Shif
  const domainMonthlyAssignments: ShiftAssignment[] = [];

  clinicalNurses.forEach((nurseEmp) => {
    const matchedNurse = domainNurses.find(
      (dn) => dn.name.toLowerCase() === nurseEmp.name.toLowerCase() || String(dn.nip) === String(nurseEmp.nip)
    );
    const nurseId = matchedNurse ? matchedNurse.id : (isNaN(Number(nurseEmp.nip)) ? Number(nurseEmp.id) || 1 : Number(nurseEmp.nip));
    const nurseName = matchedNurse ? matchedNurse.name : nurseEmp.name;

    for (let d = 1; d <= daysInMonth; d++) {
      const dateStr = `${year}-${String(month).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
      const dayOfWeek = new Date(year, month - 1, d).getDay();
      const isSunday = dayOfWeek === 0;

      const sch = effectiveMonthlySchedules.find((s) => s.employeeId === nurseEmp.id && s.date === dateStr);
      const shift = sch
        ? sch.shift
        : isSunday
        ? 'libur'
        : getEffectiveShiftForEmployee(nurseEmp, dateStr, schedules, employees);

      const st =
        shift === 'pagi'
          ? 'PAGI'
          : shift === 'siang'
          ? 'SIANG'
          : shift === 'pagi_siang'
          ? 'pagi_siang'
          : shift === 'cuti'
          ? 'CUTI'
          : shift === 'sakit'
          ? 'SAKIT'
          : shift === 'izin'
          ? 'IZIN'
          : 'LIBUR';

      const shiftSlot: 'pagi' | 'siang' = shift === 'siang' ? 'siang' : 'pagi';

      // Find assigned machines for this nurse on this date and shift
      const assignedIds = effectiveMachineAssignments
        .filter((ma) => {
          const isNurseMatch = ma.nurseId === nurseEmp.id || (ma as any).employeeId === nurseEmp.id;
          const isDateMatch = ma.date === dateStr;
          const isShiftMatch = !ma.shift || ma.shift.toLowerCase() === shiftSlot;
          return isNurseMatch && isDateMatch && isShiftMatch && !ma.isOff;
        })
        .map((ma) => {
          const rawId = String(ma.machineId).trim();
          const cleanCode = rawId.replace(/^MACH-?/i, '').toUpperCase();
          const matchedHD = machines.find(
            (m) =>
              String(m.id || '').toLowerCase() === rawId.toLowerCase() ||
              m.code.toUpperCase() === rawId.toUpperCase() ||
              m.code.toUpperCase() === cleanCode ||
              String(m.id || '').replace(/^mach-?/i, '').toUpperCase() === cleanCode
          );
          const codeToMatch = matchedHD ? matchedHD.code : cleanCode;
          const matchingMachine = domainMachines.find(
            (dm) =>
              dm.code.toUpperCase() === codeToMatch.toUpperCase() ||
              String(dm.id) === rawId ||
              dm.code.toUpperCase() === rawId.toUpperCase()
          );
          return matchingMachine ? matchingMachine.id : (matchedHD ? matchedHD.code : rawId);
        });

      // Also obtain actual machine codes (e.g. ['A01', 'A02']) for Google Sheets display
      const machineCodes = effectiveMachineAssignments
        .filter((ma) => {
          const isNurseMatch = ma.nurseId === nurseEmp.id || (ma as any).employeeId === nurseEmp.id;
          const isDateMatch = ma.date === dateStr;
          const isShiftMatch = !ma.shift || ma.shift.toLowerCase() === shiftSlot;
          return isNurseMatch && isDateMatch && isShiftMatch && !ma.isOff;
        })
        .map((ma) => {
          const rawId = String(ma.machineId).trim();
          const cleanCode = rawId.replace(/^MACH-?/i, '').toUpperCase();
          const matchedHD = machines.find(
            (m) =>
              String(m.id || '').toLowerCase() === rawId.toLowerCase() ||
              m.code.toUpperCase() === rawId.toUpperCase() ||
              m.code.toUpperCase() === cleanCode ||
              String(m.id || '').replace(/^mach-?/i, '').toUpperCase() === cleanCode
          );
          return matchedHD ? matchedHD.code : cleanCode;
        })
        .filter(Boolean);

      // Special tasks for this nurse on this date and shift
      const nurseTasksThisDay = (specialTasks || []).filter(
        (t) =>
          (String(t.assignedToId) === String(nurseEmp.id) ||
           String(t.assignedToId) === String(nurseEmp.nip) ||
           (t as any).nurseName?.toLowerCase() === nurseEmp.name.toLowerCase()) &&
          t.date === dateStr &&
          (!t.shift || t.shift.toLowerCase() === shiftSlot)
      );

      const taskLabels: string[] = [];
      nurseTasksThisDay.forEach((t) => {
        const def = SPECIAL_TASK_DEFINITIONS[t.category];
        const label = def ? def.name : (t.title || t.category);
        if (!taskLabels.includes(label)) {
          taskLabels.push(label);
        }
      });

      // Role KATIM is cleanly separated from Tugas Khusus PJ Shift, no auto-inject
      const computedSpecialDuty = taskLabels.length > 0
        ? taskLabels.join(', ')
        : (nurseEmp.specialDuty || null);

      domainMonthlyAssignments.push({
        id: `${nurseEmp.id}_${dateStr}`,
        date: dateStr,
        nurseId,
        nurseName,
        nursePhone: nurseEmp.phone || '',
        shiftType: st as any,
        assignedMachineIds: assignedIds as any,
        machines: machineCodes,
        isLeader: nurseEmp.role === 'kepala_ruangan' || nurseEmp.role === 'pj_shift' || (nurseEmp.role as string) === 'katim',
        isWhatsAppSent: false,
        notes: sch?.note || '',
        specialDuty: computedSpecialDuty,
      });
    }
  });

  // Build doctor duties for the month (1..31 days)
  const doctorDuties: Record<string, DoctorShiftDuty> = {};

  const indonesianDays = ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'];

  for (let d = 1; d <= daysInMonth; d++) {
    const dateStr = `${year}-${String(month).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
    const dayOfWeek = new Date(year, month - 1, d).getDay();
    const isSunday = dayOfWeek === 0;
    const dayName = indonesianDays[dayOfWeek];

    const pagiDoc = employees.find((e) => {
      if (e.role !== 'dokter') return false;
      const sch = effectiveMonthlySchedules.find((s) => s.employeeId === e.id && s.date === dateStr);
      return sch && (sch.shift === 'pagi' || sch.shift === 'pagi_siang');
    });

    const siangDoc = employees.find((e) => {
      if (e.role !== 'dokter') return false;
      const sch = effectiveMonthlySchedules.find((s) => s.employeeId === e.id && s.date === dateStr);
      return sch && (sch.shift === 'siang' || sch.shift === 'pagi_siang');
    });

    const docPName = isSunday ? '-' : pagiDoc ? pagiDoc.name : '-';
    const docSName = isSunday ? '-' : siangDoc ? siangDoc.name : '-';

    let status = 'Belum Terisi';
    if (isSunday) {
      status = 'Libur Rutin HD (Minggu)';
    } else if (pagiDoc && siangDoc && pagiDoc.id === siangDoc.id) {
      status = '2 Shif Sekaligus';
    } else if (pagiDoc && siangDoc && pagiDoc.id !== siangDoc.id) {
      status = 'Lengkap (2 Dr)';
    } else if (pagiDoc && !siangDoc) {
      status = 'Pagi Saja';
    } else if (!pagiDoc && siangDoc) {
      status = 'Siang Saja';
    }

    doctorDuties[dateStr] = {
      date: dateStr,
      pagiDoctorId: pagiDoc?.id || '',
      pagiDoctorName: docPName,
      siangDoctorId: siangDoc?.id || '',
      siangDoctorName: docSName,
      dayName,
      dayNumber: d,
      status,
      isSunday,
      notes: isSunday ? 'Libur Rutin HD (Hari Minggu)' : '',
    };
  }

  const baysSet = new Set<string>();
  machines.forEach((m) => {
    if (m.bay) baysSet.add(m.bay);
    else if (m.zone) baysSet.add(m.zone);
  });
  if (baysSet.size === 0) {
    baysSet.add('Bay A (Reguler)');
    baysSet.add('Bay B (Reguler)');
    baysSet.add('Bay C (Isolasi)');
  }

  return {
    monthPrefix,
    domainNurses,
    domainMachines,
    domainMonthlyAssignments,
    bays: Array.from(baysSet),
    domainDoctors,
    doctorDuties,
    autoGeneratedSchedules,
    autoGeneratedMachineAssignments,
    specialTasks,
    employees,
  };
}

/**
 * Pushes data to Google Sheets via Webhook (supports both full and targeted/partial synchronization).
 */
export async function pushToGoogleSheets(
  settings: AppSettings,
  payloadData: SyncPayloadData,
  doctorDuties?: Record<string, DoctorShiftDuty>,
  syncTargets?: PartialSyncTargets
): Promise<{ isSuccess: boolean; message: string }> {
  const webhookUrl = (settings?.googleSheetWebhookUrl || '').trim();
  if (!webhookUrl) {
    return {
      isSuccess: false,
      message: 'URL Webhook Google Apps Script belum dikonfigurasi. Buka pengaturan untuk menyetel URL.',
    };
  }

  try {
    const dutiesToSend = doctorDuties || payloadData.doctorDuties;
    const doctorsToSend = payloadData.domainDoctors;

    const dailySpecialTasks = (payloadData.specialTasks || []).map((t) => {
      const nurse = (payloadData.employees || []).find(
        (e) =>
          String(e.id) === String(t.assignedToId) ||
          String(e.nip) === String(t.assignedToId) ||
          e.name.toLowerCase() === (t as any).nurseName?.toLowerCase()
      );
      const def = SPECIAL_TASK_DEFINITIONS[t.category as SpecialTaskCategory];
      const categoryName = def?.name || t.title || t.category;
      const nurseRole = nurse
        ? nurse.role === 'kepala_ruangan'
          ? 'Kepala Ruangan'
          : (nurse.role === 'pj_shift' || (nurse.role as string) === 'katim')
          ? 'PJ Sif / Katim'
          : 'Perawat Pelaksana'
        : (t.category === 'pj_shift' ? 'PJ Sif / Katim' : 'Perawat Pelaksana');

      return {
        id: t.id,
        date: t.date,
        shift: t.shift,
        shiftLabel: String(t.shift).toLowerCase() === 'siang' ? 'Siang' : 'Pagi',
        nurseId: t.assignedToId,
        nurseName: nurse ? nurse.name : (t as any).nurseName || t.assignedToId,
        nurseRole,
        category: t.category,
        categoryName,
        shortCode: def?.shortCode || '',
        title: t.title,
        description: t.description || '',
        priority: t.priority,
        status: t.status,
        createdAt: t.createdAt,
        completedAt: t.completedAt || '',
        completionNotes: t.completionNotes || '',
      };
    });

    const result = await GoogleSheetsService.syncAllToGoogleSheets(
      webhookUrl,
      payloadData.monthPrefix,
      payloadData.domainNurses,
      payloadData.domainMachines,
      payloadData.domainMonthlyAssignments,
      payloadData.bays,
      doctorsToSend,
      dutiesToSend,
      undefined,
      dailySpecialTasks,
      syncTargets
    );
    return {
      isSuccess: result.isSuccess,
      message: result.message,
    };
  } catch (err: any) {
    return {
      isSuccess: false,
      message: 'Gagal mengirim data ke Google Sheets: ' + (err?.message || err),
    };
  }
}

/**
 * Pulls data from Google Sheets (via Webhook or Spreadsheet URL fallback).
 */
export async function pullFromGoogleSheets(
  settings: AppSettings,
  targetMonth: string,
  employees: UserAccount[],
  machines: HDMachine[]
): Promise<{
  isSuccess: boolean;
  message: string;
  assignments: ShiftAssignment[];
  nurses?: Nurse[];
  machines?: Machine[];
  doctors?: Doctor[];
  doctorDuties?: Record<string, DoctorShiftDuty>;
}> {
  const webhookUrl = (settings?.googleSheetWebhookUrl || '').trim();
  const spreadsheetUrl = (settings?.googleSpreadsheetIdOrUrl || '').trim();

  // 1. Try pulling via Google Apps Script Webhook
  if (webhookUrl) {
    try {
      const webhookResult = await GoogleSheetsService.fetchDataFromGoogleSheets(webhookUrl, targetMonth);
      if (webhookResult.isSuccess && (webhookResult.assignments?.length || webhookResult.nurses?.length)) {
        return {
          isSuccess: true,
          message: webhookResult.message || `Berhasil menarik data via Webhook (${webhookResult.assignments.length} jadwal).`,
          assignments: webhookResult.assignments,
          nurses: webhookResult.nurses,
          machines: webhookResult.machines,
          doctors: webhookResult.doctors,
          doctorDuties: webhookResult.doctorDuties,
        };
      }
    } catch (whErr) {
      console.warn('[GoogleSheetsSync] Webhook fetch error, trying spreadsheet URL fallback:', whErr);
    }
  }

  // 2. Fallback: Try pulling via Google Spreadsheet URL (CSV matrix parser + Doctor tabs)
  if (spreadsheetUrl) {
    try {
      const domainNurses: Nurse[] = sortNursesByShiftScheduleOrder(
        (employees || []).filter(
          (e) => e.role === 'perawat' || e.role === 'pj_shift' || e.role === 'kepala_ruangan'
        )
      ).map((e, idx) => ({
          id: isNaN(Number(e.id)) ? idx + 1 : Number(e.id),
          name: e.name,
          nip: e.nip,
          phone: e.phone,
          role: e.role === 'kepala_ruangan' ? 'KARU' : e.role === 'pj_shift' ? 'KATIM' : 'PELAKSANA',
          isActive: e.status === 'aktif',
          skillLevel: e.skillLevel || 'Senior',
          specialDuty: e.specialDuty,
        }));

      const domainMachines: Machine[] = machines.map((m, idx) => ({
        id: isNaN(Number(m.id)) ? idx + 1 : Number(m.id),
        code: m.code,
        name: `Mesin ${m.code}`,
        brandModel: (m as any).brandModel || 'HD Unit',
        category: 'REGULER',
        status: 'AKTIF',
        bay: m.bay || 'Bay A',
      }));

      // Fetch nurse schedule matrix
      const parseResult = await ScheduleImportService.fetchFromGoogleSheetsUrl(
        spreadsheetUrl,
        targetMonth,
        domainNurses,
        domainMachines,
        true
      );

      // Extract Spreadsheet ID to fetch Doctor & Nurse tabs
      const cleanInput = spreadsheetUrl.trim();
      const idMatch = cleanInput.match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/);
      const sheetId = idMatch && idMatch[1] ? idMatch[1] : /^[a-zA-Z0-9-_]{20,}$/.test(cleanInput) ? cleanInput : null;

      let pulledDoctors: Doctor[] = [];
      let pulledDoctorDuties: Record<string, DoctorShiftDuty> = {};
      let pulledNursesFromCsv: Nurse[] = [];

      if (sheetId) {
        try {
          // Fetch "Data Perawat" tab
          const nurseTabUrl = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=Data%20Perawat`;
          const nurseRes = await fetch(nurseTabUrl);
          if (nurseRes.ok) {
            const nurseCsv = await nurseRes.text();
            pulledNursesFromCsv = parseNursesCsv(nurseCsv);
          }
        } catch (e) {
          console.warn('[GoogleSheetsSync] Could not fetch Data Perawat tab:', e);
        }

        try {
          // Fetch "Data Dokter" tab
          const doctorTabUrl = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=Data%20Dokter`;
          const docRes = await fetch(doctorTabUrl);
          if (docRes.ok) {
            const docCsv = await docRes.text();
            pulledDoctors = parseDoctorsCsv(docCsv);
          }
        } catch (e) {
          console.warn('[GoogleSheetsSync] Could not fetch Data Dokter tab:', e);
        }

        try {
          // Fetch "Jadwal Dokter HD" tab
          const dutyTabUrl = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=Jadwal%20Dokter%20HD`;
          const dutyRes = await fetch(dutyTabUrl);
          if (dutyRes.ok) {
            const dutyCsv = await dutyRes.text();
            pulledDoctorDuties = parseDoctorDutiesCsv(dutyCsv);
          }
        } catch (e) {
          console.warn('[GoogleSheetsSync] Could not fetch Jadwal Dokter HD tab:', e);
        }

        // Fetch "Jadwal Tugas Khusus" tab
        try {
          const taskTabUrl = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=Jadwal%20Tugas%20Khusus`;
          const taskRes = await fetch(taskTabUrl);
          if (taskRes.ok) {
            const taskCsv = await taskRes.text();
            const tRows = parseSimpleCsv(taskCsv);
            for (let i = 1; i < tRows.length; i++) {
              const r = tRows[i];
              const rDate = normalizeDoctorDutyDate(r[0]);
              const rNurse = String(r[4] || '').toLowerCase().trim();
              const rDuty = String(r[6] || '').trim();
              if (rDate && rNurse && rDuty && parseResult.assignments) {
                const asg = parseResult.assignments.find(
                  (a) => a.date === rDate && a.nurseName.toLowerCase().trim() === rNurse
                );
                if (asg) {
                  asg.specialDuty = asg.specialDuty ? `${asg.specialDuty}, ${rDuty}` : rDuty;
                }
              }
            }
          }
        } catch (e) {
          console.warn('[GoogleSheetsSync] Could not fetch Jadwal Tugas Khusus tab:', e);
        }

        // Fetch "Alokasi Mesin" / "Jadwal HD (Detail Mesin)" tab
        try {
          let machCsv = '';
          const machTabUrl = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=Alokasi%20Mesin`;
          let machRes = await fetch(machTabUrl);
          if (machRes.ok) {
            machCsv = await machRes.text();
          } else {
            const altMachTabUrl = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=Jadwal%20HD%20(Detail%20Mesin)`;
            const altMachRes = await fetch(altMachTabUrl);
            if (altMachRes.ok) {
              machCsv = await altMachRes.text();
            }
          }
          if (machCsv) {
            const mRows = parseSimpleCsv(machCsv);
            for (let i = 1; i < mRows.length; i++) {
              const r = mRows[i];
              const rDate = normalizeDoctorDutyDate(r[1]);
              const rNurse = String(r[5] || '').toLowerCase().trim();
              const rMachines = String(r[7] || '').trim();
              const rDuty = String(r[9] || '').trim();
              if (rDate && rNurse && parseResult.assignments) {
                const asg = parseResult.assignments.find(
                  (a) => a.date === rDate && a.nurseName.toLowerCase().trim() === rNurse
                );
                if (asg) {
                  if (rMachines) {
                    const codes = rMachines.split(/[,;\s]+/).filter(Boolean);
                    codes.forEach((c) => {
                      const cleanC = c.replace(/^MACH-?/i, '').toUpperCase();
                      const matchedM = domainMachines.find(
                        (m) => m.code.toUpperCase() === cleanC || m.code.toUpperCase() === c.toUpperCase()
                      );
                      if (matchedM && !asg.assignedMachineIds.includes(matchedM.id)) {
                        asg.assignedMachineIds.push(matchedM.id);
                      }
                    });
                  }
                  if (rDuty && !asg.specialDuty) {
                    asg.specialDuty = rDuty;
                  }
                }
              }
            }
          }
        } catch (e) {
          console.warn('[GoogleSheetsSync] Could not fetch Alokasi Mesin / Detail Mesin tab:', e);
        }
      }

      const effectiveNurses = pulledNursesFromCsv.length > 0 ? pulledNursesFromCsv : parseResult.newNursesCreated;
      if (parseResult.isSuccess && parseResult.assignments.length > 0) {
        const docMsg = pulledDoctors.length > 0 ? ` & ${pulledDoctors.length} Dokter` : '';
        const nurseMsg = effectiveNurses && effectiveNurses.length > 0 ? ` & ${effectiveNurses.length} Perawat` : '';
        return {
          isSuccess: true,
          message: `Berhasil menarik ${parseResult.assignments.length} penugasan jadwal perawat, mesin & tugas khusus${docMsg}${nurseMsg} dari Google Spreadsheet!`,
          assignments: parseResult.assignments,
          nurses: effectiveNurses,
          doctors: pulledDoctors.length > 0 ? pulledDoctors : undefined,
          doctorDuties: Object.keys(pulledDoctorDuties).length > 0 ? pulledDoctorDuties : undefined,
        };
      } else if (pulledDoctors.length > 0 || (effectiveNurses && effectiveNurses.length > 0) || Object.keys(pulledDoctorDuties).length > 0) {
        return {
          isSuccess: true,
          message: `Berhasil menarik data staf & dokter (${pulledDoctors.length} Dokter, ${effectiveNurses?.length || 0} Perawat) dari Google Spreadsheet!`,
          assignments: [],
          nurses: effectiveNurses,
          doctors: pulledDoctors,
          doctorDuties: pulledDoctorDuties,
        };
      } else {
        return {
          isSuccess: false,
          message: parseResult.message || 'Tidak ada jadwal ditemukan di Google Spreadsheet.',
          assignments: [],
        };
      }
    } catch (urlErr: any) {
      return {
        isSuccess: false,
        message: 'Gagal menarik data dari Google Spreadsheet: ' + (urlErr?.message || urlErr),
        assignments: [],
      };
    }
  }

  return {
    isSuccess: false,
    message: 'Belum ada Webhook URL atau Link Spreadsheet yang dikonfigurasi. Silakan isi URL terlebih dahulu.',
    assignments: [],
  };
}

/**
 * Transforms pulled assignments into application schedules, machine assignments, and special tasks.
 */
export function applyPulledDataToApp(
  assignments: ShiftAssignment[],
  targetMonth: string,
  currentSchedules: ShiftSchedule[],
  currentEmployees: UserAccount[],
  currentMachines: HDMachine[],
  currentMachineAssignments: MachineAssignment[],
  currentSpecialTasksOrDoctors?: SpecialTask[] | Doctor[],
  pulledDoctorsOrDuties?: Doctor[] | Record<string, DoctorShiftDuty>,
  pulledDoctorDutiesInput?: Record<string, DoctorShiftDuty>,
  pulledNursesInput?: Nurse[]
): {
  updatedSchedules: ShiftSchedule[];
  updatedMachineAssignments: MachineAssignment[];
  updatedEmployees: UserAccount[];
  updatedSpecialTasks: SpecialTask[];
} {
  let currentSpecialTasks: SpecialTask[] = [];
  let pulledDoctors: Doctor[] | undefined = undefined;
  let pulledDoctorDuties: Record<string, DoctorShiftDuty> | undefined = undefined;
  let pulledNurses: Nurse[] | undefined = pulledNursesInput;

  if (Array.isArray(currentSpecialTasksOrDoctors)) {
    if (
      currentSpecialTasksOrDoctors.length > 0 &&
      ('category' in currentSpecialTasksOrDoctors[0] || 'assignedToId' in currentSpecialTasksOrDoctors[0])
    ) {
      currentSpecialTasks = currentSpecialTasksOrDoctors as SpecialTask[];
      pulledDoctors = Array.isArray(pulledDoctorsOrDuties) ? (pulledDoctorsOrDuties as Doctor[]) : undefined;
      pulledDoctorDuties =
        pulledDoctorDutiesInput ||
        (!Array.isArray(pulledDoctorsOrDuties) ? (pulledDoctorsOrDuties as Record<string, DoctorShiftDuty>) : undefined);
    } else if (
      currentSpecialTasksOrDoctors.length > 0 &&
      ('sip' in currentSpecialTasksOrDoctors[0] || 'specialization' in currentSpecialTasksOrDoctors[0])
    ) {
      pulledDoctors = currentSpecialTasksOrDoctors as Doctor[];
      pulledDoctorDuties = pulledDoctorsOrDuties as Record<string, DoctorShiftDuty>;
    } else {
      currentSpecialTasks = currentSpecialTasksOrDoctors as SpecialTask[];
      pulledDoctors = Array.isArray(pulledDoctorsOrDuties) ? (pulledDoctorsOrDuties as Doctor[]) : undefined;
      pulledDoctorDuties = pulledDoctorDutiesInput;
    }
  }

  const employeeMapByName = new Map<string, UserAccount>();
  const employeeMapById = new Map<string, UserAccount>();
  let updatedEmployees = currentEmployees.filter(
    (e) =>
      e.id !== 'nurse1790191588620' &&
      !e.id.includes('1790191588620') &&
      !e.username?.includes('1790191588620') &&
      !e.name?.includes('1790191588620')
  );

  // 1. Merge pulled nurses into updatedEmployees (Sync Peran/Jabatan, NIP, Phone, Status, Tugas Khusus)
  if (pulledNurses && pulledNurses.length > 0) {
    pulledNurses.forEach((pNurse) => {
      if (
        !pNurse ||
        !pNurse.name ||
        pNurse.name.trim() === '-' ||
        pNurse.name.trim() === '--' ||
        pNurse.name.trim() === '---' ||
        pNurse.name.replace(/[^a-zA-Z0-9]/g, '').length < 2 ||
        pNurse.name.toLowerCase().includes('admin') ||
        isInvalidNurseAccount(pNurse)
      ) {
        return;
      }

      const pNurseNameClean = pNurse.name.toLowerCase().trim();
      const existingNurseIdx = updatedEmployees.findIndex(
        (e) =>
          (e.role === 'perawat' || e.role === 'pj_shift' || e.role === 'kepala_ruangan') &&
          (e.name.toLowerCase().trim() === pNurseNameClean ||
            (pNurse.nip && e.nip && e.nip.trim() === pNurse.nip.trim()) ||
            String(e.id) === String(pNurse.id))
      );

      const mappedRole: UserRole =
        pNurse.role === 'KARU'
          ? 'kepala_ruangan'
          : pNurse.role === 'KATIM'
          ? 'pj_shift'
          : 'perawat';

      if (existingNurseIdx >= 0) {
        updatedEmployees[existingNurseIdx] = {
          ...updatedEmployees[existingNurseIdx],
          name: pNurse.name,
          role: mappedRole,
          nip: pNurse.nip || updatedEmployees[existingNurseIdx].nip,
          phone: pNurse.phone || updatedEmployees[existingNurseIdx].phone,
          status: pNurse.isActive ? 'aktif' : 'nonaktif',
          specialDuty: pNurse.specialDuty || updatedEmployees[existingNurseIdx].specialDuty,
        };
      } else {
        const newNurseEmp: UserAccount = {
          id: `emp-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
          username: pNurse.name.toLowerCase().replace(/[^a-z0-9]/g, '') || `nurse${Date.now()}`,
          password: 'password123',
          name: pNurse.name,
          nip: pNurse.nip || `NIP-${Math.floor(100000 + Math.random() * 900000)}`,
          role: mappedRole,
          phone: pNurse.phone || '081234567800',
          email: `${pNurse.name.toLowerCase().replace(/[^a-z0-9]/g, '') || 'nurse'}@hospital.id`,
          status: pNurse.isActive ? 'aktif' : 'nonaktif',
          createdAt: new Date().toISOString(),
          skillLevel: pNurse.skillLevel || 'Senior',
          specialDuty: pNurse.specialDuty || undefined,
        };
        updatedEmployees.push(newNurseEmp);
      }
    });
  }

  // 2. Merge pulled doctors into employees (Sync Spesialisasi & Tugas Jaga Dokter)
  if (pulledDoctors && pulledDoctors.length > 0) {
    pulledDoctors.forEach((doc) => {
      const docNameNorm = doc.name.toLowerCase().replace(/^dr\.?\s*/i, '').trim();
      const existingDocIdx = updatedEmployees.findIndex((e) => {
        if (e.role !== 'dokter') return false;
        const eNameNorm = e.name.toLowerCase().replace(/^dr\.?\s*/i, '').trim();
        return (
          eNameNorm === docNameNorm ||
          e.name.toLowerCase().trim() === doc.name.toLowerCase().trim() ||
          (doc.sip && e.nip && e.nip.trim() === doc.sip.trim()) ||
          String(e.id) === `emp-dr-${doc.id}` ||
          String(e.id) === String(doc.id)
        );
      });

      const docSpec =
        doc.specialization?.trim() ||
        (doc.role === 'DPJP'
          ? 'Dokter Penanggung Jawab Pelayanan HD (DPJP)'
          : 'Dokter Jaga Hemodialisa');

      if (existingDocIdx >= 0) {
        updatedEmployees[existingDocIdx] = {
          ...updatedEmployees[existingDocIdx],
          name: doc.name,
          nip: doc.sip || updatedEmployees[existingDocIdx].nip,
          phone: doc.phone || updatedEmployees[existingDocIdx].phone,
          specialization: docSpec,
          status: doc.isActive ? 'aktif' : 'nonaktif',
        };
      } else {
        const newDocEmp: UserAccount = {
          id: `emp-dr-${doc.id}`,
          username: doc.name.toLowerCase().replace(/[^a-z0-9]/g, '_'),
          password: 'dokter123',
          name: doc.name,
          nickname: doc.name.split(' ')[1] ? `dr. ${doc.name.split(' ')[1]}` : 'Dokter',
          gender: doc.name.toLowerCase().includes('paramitha') ? 'P' : 'L',
          role: 'dokter',
          nip: doc.sip || '',
          phone: doc.phone || '',
          email: `${doc.name.toLowerCase().replace(/[^a-z0-9]/g, '')}@happyland.co.id`,
          status: doc.isActive ? 'aktif' : 'nonaktif',
          specialization: docSpec,
          createdAt: new Date().toISOString(),
        };
        updatedEmployees.push(newDocEmp);
      }
    });
  }

  updatedEmployees.forEach((emp) => {
    employeeMapByName.set(emp.name.toLowerCase().trim(), emp);
    employeeMapById.set(String(emp.id), emp);
  });

  // Convert assignments to ShiftSchedule[], MachineAssignment[], and SpecialTask[]
  const newShiftSchedules: ShiftSchedule[] = [];
  const newMachineAssignments: MachineAssignment[] = [];
  const newSpecialTasks: SpecialTask[] = [];
  const datesProcessed = new Set<string>();

  assignments.forEach((a) => {
    datesProcessed.add(a.date);
    const rawNurseName = String(a.nurseName || '').trim();
    const isDummyName =
      !rawNurseName ||
      rawNurseName === '-' ||
      rawNurseName === '--' ||
      rawNurseName === '---' ||
      rawNurseName.replace(/[^a-zA-Z0-9]/g, '').length < 2;

    let foundEmp = !isDummyName
      ? (employeeMapByName.get(rawNurseName.toLowerCase()) || employeeMapById.get(String(a.nurseId)))
      : undefined;

    if (!foundEmp) {
      if (isDummyName) {
        // Do NOT auto-register a dummy nurse account for empty/dash rows!
        return;
      }
      // Auto-register legitimate nurse if truly missing
      const newEmpId = `emp-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
      foundEmp = {
        id: newEmpId,
        username: rawNurseName.toLowerCase().replace(/[^a-z0-9]/g, '') || `nurse${Date.now()}`,
        password: 'password123',
        name: rawNurseName,
        nip: a.notes || `NIP-${Math.floor(100000 + Math.random() * 900000)}`,
        role: a.isLeader ? 'pj_shift' : 'perawat',
        phone: a.nursePhone || '081234567800',
        email: `${rawNurseName.toLowerCase().replace(/[^a-z0-9]/g, '') || 'nurse'}@hospital.id`,
        status: 'aktif',
        createdAt: new Date().toISOString(),
        skillLevel: 'Senior',
        specialDuty: a.specialDuty || undefined,
      };
      updatedEmployees.push(foundEmp);
      employeeMapByName.set(foundEmp.name.toLowerCase().trim(), foundEmp);
      employeeMapById.set(String(foundEmp.id), foundEmp);
    }

    const emp = foundEmp;

    let shiftTypeLower: ShiftType = 'libur';
    const st = String(a.shiftType || '').toLowerCase();
    if (st.includes('pagi') && st.includes('siang')) shiftTypeLower = 'pagi_siang';
    else if (st === 'siang' || st === 's') shiftTypeLower = 'siang';
    else if (st === 'pagi' || st === 'p') shiftTypeLower = 'pagi';
    else if (st === 'cuti' || st === 'c') shiftTypeLower = 'cuti';
    else if (st === 'izin' || st === 'i') shiftTypeLower = 'izin';
    else if (st === 'sakit' || st === 'skt' || st === 'sk') shiftTypeLower = 'sakit';
    else shiftTypeLower = 'libur';

    newShiftSchedules.push({
      id: `${emp.id}_${a.date}`,
      employeeId: emp.id,
      date: a.date,
      shift: shiftTypeLower,
      note: a.notes || (a.specialDuty ? `Tugas: ${a.specialDuty}` : undefined),
    });

    // Process Machine Assignments
    const rawCodes = (a as any).rawMachineCodes || [];
    const machinesList = Array.isArray((a as any).machines)
      ? (a as any).machines
      : typeof (a as any).machines === 'string'
      ? (a as any).machines.split(/[,;\s]+/).filter(Boolean)
      : [];
    const machineInputs: any[] = [...(a.assignedMachineIds || []), ...rawCodes, ...machinesList];

    if (machineInputs.length > 0 && (shiftTypeLower === 'pagi' || shiftTypeLower === 'siang' || shiftTypeLower === 'pagi_siang')) {
      const shiftSlot: 'pagi' | 'siang' = shiftTypeLower === 'siang' ? 'siang' : 'pagi';
      machineInputs.forEach((mId) => {
        const rawStr = String(mId).trim();
        if (!rawStr) return;
        const cleanCode = rawStr.replace(/^MACH-?/i, '').toUpperCase();
        
        let matchingMachine = currentMachines.find(
          (m) =>
            String(m.id || '').toLowerCase() === rawStr.toLowerCase() ||
            m.code.toUpperCase() === rawStr.toUpperCase() ||
            m.code.toUpperCase() === cleanCode ||
            String(m.id || '').replace(/^mach-?/i, '').toUpperCase() === cleanCode
        );

        // Fallback: If rawStr is a 1-based index (e.g. "1" -> currentMachines[0])
        if (!matchingMachine && /^\d+$/.test(rawStr)) {
          const idx = parseInt(rawStr, 10) - 1;
          if (idx >= 0 && idx < currentMachines.length) {
            matchingMachine = currentMachines[idx];
          }
        }

        if (matchingMachine) {
          const assignId = `${a.date}_${shiftSlot}_${matchingMachine.id}`;
          if (!newMachineAssignments.some((ma) => ma.id === assignId)) {
            const existing = currentMachineAssignments.find(
              (ma) =>
                ma.id === assignId ||
                (ma.date === a.date && ma.shift === shiftSlot && ma.machineId === matchingMachine.id)
            );
            newMachineAssignments.push({
              id: assignId,
              machineId: matchingMachine.id,
              nurseId: emp.id,
              date: a.date,
              shift: shiftSlot,
              isOff: existing?.isOff || false,
              offReason: existing?.offReason,
              patientName: existing?.patientName,
              medicalRecordNo: existing?.medicalRecordNo,
              targetUF: existing?.targetUF || '2.5 L',
              dialyzerType:
                existing?.dialyzerType ||
                (matchingMachine.zone.toLowerCase().includes('isolasi')
                  ? 'Hi-Flux F7HPS (Isolasi)'
                  : 'Hi-Flux F7HPS'),
              notes: existing?.notes || `Penugasan Google Sheets (${matchingMachine.code}) - ${emp.name}`,
            });
          }
        }
      });
    }

    // Process Special Tasks
    if (shiftTypeLower === 'pagi' || shiftTypeLower === 'siang' || shiftTypeLower === 'pagi_siang') {
      const shiftSlot: 'pagi' | 'siang' = shiftTypeLower === 'siang' ? 'siang' : 'pagi';
      const dutyRaw = String(a.specialDuty || '').trim();
      const detectedCats: SpecialTaskCategory[] = [];

      // Note: Tugas khusus PJ Shift tidak di-generate otomatis agar diinput manual oleh pengguna
      if (dutyRaw.toLowerCase().includes('bhp') || dutyRaw.toLowerCase().includes('sterilisasi') || dutyRaw.toLowerCase().includes('instrumen')) {
        detectedCats.push('bhp');
      }
      if (dutyRaw.toLowerCase().includes('farm') || dutyRaw.toLowerCase().includes('logistik') || dutyRaw.toLowerCase().includes('obat') || dutyRaw.toLowerCase().includes('cairan')) {
        detectedCats.push('farmasi_logistik');
      }
      if (dutyRaw.toLowerCase().includes('ro') || dutyRaw.toLowerCase().includes('water') || dutyRaw.toLowerCase().includes('natrium')) {
        detectedCats.push('natrium_ro');
      }
      if (dutyRaw.toLowerCase().includes('cito') || dutyRaw.toLowerCase().includes('isolasi') || dutyRaw.toLowerCase().includes('darurat') || dutyRaw.toLowerCase().includes('emergency')) {
        detectedCats.push('cito');
      }

      // If dutyRaw is provided but didn't match any standard keyword, treat as a custom task
      if (detectedCats.length === 0 && dutyRaw && dutyRaw !== '-' && dutyRaw.toLowerCase() !== 'null' && dutyRaw.toLowerCase() !== 'undefined') {
        detectedCats.push('bhp');
      }

      detectedCats.forEach((cat) => {
        const def = SPECIAL_TASK_DEFINITIONS[cat];
        const taskId = `task-${a.date}-${shiftSlot}-${cat}-${emp.id}`;
        const existingTask = currentSpecialTasks.find(
          (t) =>
            t.id === taskId ||
            (t.date === a.date && t.shift === shiftSlot && t.assignedToId === emp.id && t.category === cat)
        );
        if (!newSpecialTasks.some((t) => t.id === taskId)) {
          newSpecialTasks.push({
            id: taskId,
            title: existingTask?.title || (dutyRaw && !def?.name.toLowerCase().includes(dutyRaw.toLowerCase()) ? `Tugas: ${dutyRaw}` : `Tugas Khusus: ${def?.name || cat}`),
            description: existingTask?.description || (dutyRaw ? `Tugas khusus: ${dutyRaw}` : (def?.description || `Penugasan tugas khusus ${def?.name || cat}`)),
            assignedToId: emp.id,
            assignedByName: existingTask?.assignedByName || 'Google Sheets Sync',
            date: a.date,
            shift: shiftSlot,
            priority: existingTask?.priority || (cat === 'cito' ? 'mendesak' : cat === 'pj_shift' ? 'penting' : 'normal'),
            status: existingTask?.status || 'pending',
            category: cat,
            createdAt: existingTask?.createdAt || new Date().toISOString().replace('T', ' ').substring(0, 16),
            completedAt: existingTask?.completedAt,
            completionNotes: existingTask?.completionNotes,
          });
        }
      });
    }
  });

  // Process Doctor Duties from Google Sheets (if available)
  if (pulledDoctorDuties && Object.keys(pulledDoctorDuties).length > 0) {
    const doctorEmployees = updatedEmployees.filter((e) => e.role === 'dokter');
    Object.values(pulledDoctorDuties).forEach((duty) => {
      datesProcessed.add(duty.date);
      const isSunday = new Date(duty.date).getDay() === 0;

      if (isSunday || (duty.pagiDoctorName === '-' && duty.siangDoctorName === '-')) {
        doctorEmployees.forEach((doc) => {
          newShiftSchedules.push({
            id: `${doc.id}_${duty.date}`,
            employeeId: doc.id,
            date: duty.date,
            shift: 'libur',
            note: duty.notes || 'Pelayanan Tutup (Hari Minggu)',
          });
        });
      } else {
        // Morning doctor
        if (duty.pagiDoctorName && duty.pagiDoctorName !== '-') {
          const pagiName = duty.pagiDoctorName;
          const matchedPagiDoc =
            doctorEmployees.find(
              (d) => d.name.toLowerCase() === pagiName.toLowerCase() || d.id === `emp-dr-${duty.pagiDoctorId}`
            ) || doctorEmployees[0];
          if (matchedPagiDoc) {
            newShiftSchedules.push({
              id: `${matchedPagiDoc.id}_${duty.date}`,
              employeeId: matchedPagiDoc.id,
              date: duty.date,
              shift: 'pagi',
              note: duty.notes || 'Dokter Jaga HD (Pagi)',
            });
          }
        }
        // Afternoon doctor
        if (duty.siangDoctorName && duty.siangDoctorName !== '-') {
          const siangName = duty.siangDoctorName;
          const matchedSiangDoc =
            doctorEmployees.find(
              (d) => d.name.toLowerCase() === siangName.toLowerCase() || d.id === `emp-dr-${duty.siangDoctorId}`
            ) || doctorEmployees[1] || doctorEmployees[0];
          if (matchedSiangDoc) {
            newShiftSchedules.push({
              id: `${matchedSiangDoc.id}_${duty.date}`,
              employeeId: matchedSiangDoc.id,
              date: duty.date,
              shift: 'siang',
              note: duty.notes || 'Dokter Jaga HD (Siang)',
            });
          }
        }
      }
    });
  } else {
    // Retain existing doctor schedules for this month
    const existingDoctorSchedules = currentSchedules.filter((s) => {
      const emp = updatedEmployees.find((e) => e.id === s.employeeId);
      return emp?.role === 'dokter';
    });
    newShiftSchedules.push(...existingDoctorSchedules);
  }

  // Ensure that for the targetMonth, all dates have complete doctor schedules
  if (targetMonth && targetMonth.includes('-')) {
    const [tYearStr, tMonthStr] = targetMonth.split('-');
    const tYear = parseInt(tYearStr, 10) || 2026;
    const tMonth = parseInt(tMonthStr, 10) || 10;
    const tDaysInMonth = new Date(tYear, tMonth, 0).getDate();
    const doctorEmployees = updatedEmployees.filter((e) => e.role === 'dokter');

    const docReza = doctorEmployees.find((d) => d.name.toLowerCase().includes('reza')) || doctorEmployees[0];
    const docMitha =
      doctorEmployees.find(
        (d) => d.name.toLowerCase().includes('paramitha') || d.name.toLowerCase().includes('mitha')
      ) || doctorEmployees[1] || doctorEmployees[0];

    for (let d = 1; d <= tDaysInMonth; d++) {
      const curDateStr = `${tYear}-${String(tMonth).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
      const hasAnyDoc = newShiftSchedules.some(
        (s) => s.date === curDateStr && doctorEmployees.some((de) => de.id === s.employeeId)
      );

      if (!hasAnyDoc) {
        datesProcessed.add(curDateStr);
        const dayOfWeek = new Date(tYear, tMonth - 1, d).getDay();
        const isSunday = dayOfWeek === 0;

        if (isSunday) {
          doctorEmployees.forEach((doc) => {
            newShiftSchedules.push({
              id: `${doc.id}_${curDateStr}`,
              employeeId: doc.id,
              date: curDateStr,
              shift: 'libur',
              note: 'Pelayanan Tutup (Hari Minggu)',
            });
          });
        } else {
          if (docReza) {
            newShiftSchedules.push({
              id: `${docReza.id}_${curDateStr}`,
              employeeId: docReza.id,
              date: curDateStr,
              shift: 'pagi',
              note: 'Dokter Penanggung Jawab HD (DPJP)',
            });
          }
          if (docMitha && docMitha.id !== docReza?.id) {
            newShiftSchedules.push({
              id: `${docMitha.id}_${curDateStr}`,
              employeeId: docMitha.id,
              date: curDateStr,
              shift: 'siang',
              note: 'Dokter Jaga Ruangan HD',
            });
          }
        }
      }
    }
  }

  // Ensure machines are allocated for every working date and shift in this month
  datesProcessed.forEach((dStr) => {
    (['pagi', 'siang'] as const).forEach((shiftSlot) => {
      const hasActiveMachinesForShift = newMachineAssignments.some(
        (ma) => ma.date === dStr && ma.shift === shiftSlot && !ma.isOff
      );
      if (!hasActiveMachinesForShift) {
        const nursesWorking = newShiftSchedules
          .filter((s) => s.date === dStr && (s.shift === shiftSlot || s.shift === 'pagi_siang'))
          .map((s) => updatedEmployees.find((e) => e.id === s.employeeId))
          .filter(
            (e): e is UserAccount =>
              Boolean(e && (e.role === 'perawat' || e.role === 'pj_shift' || e.role === 'kepala_ruangan'))
          );

        if (nursesWorking.length > 0) {
          const existingForShift = currentMachineAssignments.filter(
            (ma) => ma.date === dStr && ma.shift === shiftSlot && nursesWorking.some((nw) => nw.id === ma.nurseId)
          );
          if (existingForShift.length > 0) {
            existingForShift.forEach((ema) => {
              if (!newMachineAssignments.some((nma) => nma.id === ema.id)) {
                newMachineAssignments.push(ema);
              }
            });
          } else {
            const specialForShift = newSpecialTasks
              .filter((t) => t.date === dStr && t.shift === shiftSlot)
              .map((t) => ({ nurseId: t.assignedToId, category: t.category }));

            const autoAssigned = autoAssignMachinesForShift(
              dStr,
              shiftSlot,
              nursesWorking,
              currentMachines,
              currentMachineAssignments,
              specialForShift,
              false
            );
            autoAssigned.forEach((ama) => {
              if (!newMachineAssignments.some((nma) => nma.id === ama.id)) {
                newMachineAssignments.push(ama);
              }
            });
          }
        }
      }
    });
  });

  // Retain data outside of the imported month/dates
  const remainingSchedules = currentSchedules.filter(
    (s) => !datesProcessed.has(s.date) && !newShiftSchedules.some((ns) => ns.id === s.id)
  );
  const remainingMachineAssignments = currentMachineAssignments.filter((ma) => !datesProcessed.has(ma.date));
  const remainingSpecialTasks = currentSpecialTasks.filter((t) => !datesProcessed.has(t.date));

  // Retain manually entered special tasks within processed dates that don't collide
  const existingTasksInProcessedDates = currentSpecialTasks.filter((t) => {
    if (!datesProcessed.has(t.date)) return false;
    return !newSpecialTasks.some(
      (nt) =>
        nt.id === t.id ||
        (nt.date === t.date && nt.shift === t.shift && nt.assignedToId === t.assignedToId && nt.category === t.category)
    );
  });

  return {
    updatedSchedules: [...remainingSchedules, ...newShiftSchedules],
    updatedMachineAssignments: [...remainingMachineAssignments, ...newMachineAssignments],
    updatedEmployees,
    updatedSpecialTasks: [...remainingSpecialTasks, ...existingTasksInProcessedDates, ...newSpecialTasks],
  };
}
